os: Visual Studio 2015

branches:
  only:
    - appveyor

services:
  - postgresql96

environment:
  RUST_BACKTRACE: 1
  PLATFORM: x64
  NODEJS_VERSION: "8"
  MSYSTEM: "MINGW64"
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

install:
  # path setup
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Program Files\PostgreSQL\9.6\bin\;C:\Users\appveyor\.cargo\bin;%PATH%

  # compile some gcrypt libs we need
  - ps: >-
      bash -c @"
        set -e
        pacman -S mingw-w64-x86_64-toolchain
        pacman -S autoconf make libtool automake
        exec 0</dev/null 2>&1
        mkdir -p /c/projects/
        cd /c/projects
        wget -q https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.27.tar.bz2
        wget -q https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2
        tar -xvf libgpg-error-1.27.tar.bz2 > /dev/null
        tar -xvf libgcrypt-1.8.1.tar.bz2 > /dev/null
        cd libgpg-error-1.27
        ./configure --prefix=/c/usr/ --libdir=/c/lib --includedir=/c/include
        make
        make install
        cd ../libgcrypt-1.8.1
        ./configure --prefix=/c/usr --libdir=/c/lib --includedir=/c/include
        make
        make install
      "@

  # install node
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm config set msvs_version 2015
  - node -e "console.log(process.argv[0], process.arch, process.versions)"

  # install rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain stable-x86_64-pc-windows-gnu
  #- rustup toolchain install stable-x86_64-pc-windows-msvc
  - rustup default stable-gnu
  - rustup show

before_build:
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Program Files\PostgreSQL\9.6\bin\;C:\Users\appveyor\.cargo\bin;%PATH%
  - createdb turtl
  - git checkout 

build: false

test_script:
  - cargo test --release

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
