defaults: &defaults
  working_directory: /tmp/turtl/core
  docker:
    - image: circleci/node:4.8.3
    - image: circleci/postgres:9.6.2-alpine
      environment:
        - POSTGRES_USER=turtl
        - POSTGRES_DB=turtl

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout


      # set up config
      - run: cp config.yaml.default config.yaml
      - run: sed -i "s|https://api\.turtlapp\.com/v3|http://127.0.0.1:8181|g" config.yaml
      - run: sed -i "s/slappy\@turtlapp.com/${INTEGRATION_TEST_LOGIN}/g" config.yaml
      - run: sed -i "s/turtlesallthewaydown/${INTEGRATION_TEST_PASSWORD}/g" config.yaml
      - run: sed -i "s/duck duck/${INTEGRATION_TEST_V6_LOGIN}/g" config.yaml
      - run: sed -i "s/juice/${INTEGRATION_TEST_V6_PASSWORD}/g" config.yaml
      - run: cat config.yaml

      - run: git clone https://github.com/turtl/server ../server
      - run: cp ../server/config/config.yaml.ci ../server/config/config.yaml
      - restore_cache:
          key: server-npm-v1-{{ checksum "../server/package.json" }}
          key: server-npm-v1-
      - run: cd ../server && npm install
      - save_cache:
          key: server-npm-v1-{{ checksum "../server/package.json" }}
          paths:
            - ../server/node_modules
      - run: node ../server/tools/create-db-schema.js
      - run: node ../server/tools/populate-test-data.js
      - run: mkdir -p ../server/plugins
      - run:
          command: node ../server/server.js
          background: true

      # install our apt deps
      - run: sudo apt-get update
      - run: sudo apt-get install --fix-missing gpgv2 libgpg-error0 libgpg-error-dev libgcrypt20-dev

      # install libsodium
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz -O /tmp/libsodium.tar.gz
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz.sig -O /tmp/libsodium.tar.gz.sig

      # verify sodium
      - run: gpg --import libsodium.gpg.pub
      - run: gpg --verify /tmp/libsodium.tar.gz.sig /tmp/libsodium.tar.gz
      - restore_cache:
          key: sodium-v2-{{ checksum "/tmp/libsodium.tar.gz" }}
      - run: cd /tmp && tar -xvf ./libsodium.tar.gz && cd libsodium-1.0.12 && ./configure --enable-shared --enable-static && make
      - save_cache:
          key: sodium-v2-{{ checksum "/tmp/libsodium.tar.gz" }}
          paths:
            - /tmp/libsodium-1.0.12
      - run: cd /tmp/libsodium-1.0.12 && sudo make install

      # install rust
      - run: wget https://static.rust-lang.org/rustup.sh -O /tmp/rustup.sh && chmod 0750 /tmp/rustup.sh
      - run: sudo /tmp/rustup.sh --revision=1.21.0

      - restore_cache:
          key: core-build-v1-{{ .Revision }}
      - run: make test
      - save_cache:
          key: core-build-v1-{{ .Revision }}
          paths:
            - target

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test

