defaults: &defaults
  working_directory: ~/turtl/core
  docker:
    - image: circleci/node:4.8.3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: find ../core -name "*.rs" | grep -v target | sort | xargs sha256sum > ../SHA256.core-rs

      # install our apt deps
      - run: sudo apt-get update
      - run: sudo apt-get install --fix-missing gpgv2 libgpg-error0 libgpg-error-dev libgcrypt20-dev

      # install libsodium
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz -O ~/libsodium.tar.gz
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz.sig -O ~/libsodium.tar.gz.sig

      # verify sodium
      - run: gpg --import scripts/libsodium.gpg.pub
      - run: gpg --verify ~/libsodium.tar.gz.sig ~/libsodium.tar.gz
      - restore_cache:
          key: sodium-v2-{{ checksum "~/libsodium.tar.gz" }}
      - run: cd ~ && tar -xvf ./libsodium.tar.gz && cd libsodium-1.0.15 && ./configure && make
      - save_cache:
          key: sodium-v2-{{ checksum "~/libsodium.tar.gz" }}
          paths:
            - ~/libsodium-1.0.15
      - run: cd ~/libsodium-1.0.15 && sudo make install

      # install rust
      - run: wget https://static.rust-lang.org/rustup.sh -O ~/rustup.sh && chmod 0750 ~/rustup.sh
      - run: sudo ~/rustup.sh --revision=1.21.0

      - restore_cache:
          key: core-build-v1-{{ .Branch }}-{{ checksum "../SHA256.core-rs" }}
      - run: make test
      - save_cache:
          key: core-build-v1-{{ .Branch }}-{{ checksum "../SHA256.core-rs" }}
          paths:
            - target

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test

