defaults: &defaults
  working_directory: /tmp/turtl/core

version: 2
jobs:
  build:
    <<: *defaults

    docker:
      - image: circleci/node:4.8.3

    steps:
      - checkout

      # set up config
      - run: cp config.yaml.default config.yaml
      - run:
          # needs to be multi-line or the yaml parser barfs
          command: |
            sed -i 's|^data_folder:.*|data_folder: "/tmp/turtl-data"|g' config.yaml
      - run: sed -i "s|https://api\.turtlapp\.com/v3|http://127.0.0.1:8181|g" config.yaml
      - run: sed -i "s/slappy\@turtlapp.com/${INTEGRATION_TEST_LOGIN}/g" config.yaml
      - run: sed -i "s/turtlesallthewaydown/${INTEGRATION_TEST_PASSWORD}/g" config.yaml
      - run: sed -i "s/duck duck/${INTEGRATION_TEST_V6_LOGIN}/g" config.yaml
      - run: sed -i "s/juice/${INTEGRATION_TEST_V6_PASSWORD}/g" config.yaml

      # install our apt deps
      - run: sudo apt-get update
      - run: sudo apt-get install --fix-missing gpgv2

      # install libsodium
      - run: wget 'https://github.com/jedisct1/libsodium/releases/download/1.0.12/libsodium-1.0.12.tar.gz' -O /tmp/libsodium.tar.gz

      # verify sodium
      - run: gpg --import build-tools/libsodium.gpg.pub
      - run: gpg --verify build-tools/libsodium-1.0.12.tar.gz.sig /tmp/libsodium.tar.gz
      - restore_cache:
          key: sodium-v4-{{ checksum "/tmp/libsodium.tar.gz" }}
      - run: |
          cd /tmp
          tar -xvf ./libsodium.tar.gz
          cd libsodium-1.0.12
          CFLAGS="-fPIC" ./configure --disable-shared --enable-static
          make CFLAGS="-fPIC"
      - save_cache:
          key: sodium-v4-{{ checksum "/tmp/libsodium.tar.gz" }}
          paths:
            - /tmp/libsodium-1.0.12
      - run: cd /tmp/libsodium-1.0.12 && sudo make install

      # install rust
      - run: gpg --import build-tools/rust.gpg.pub
      - run: wget https://static.rust-lang.org/rustup.sh -O /tmp/rustup.sh && chmod 0750 /tmp/rustup.sh
      - run: sudo /tmp/rustup.sh --revision=1.24.1

      # build the release
      - restore_cache:
          key: core-build-v3-{{ checksum "Cargo.lock" }}
      - run: make SODIUM_STATIC=static RUST_BACKTRACE=1 CARGO_BUILD_ARGS="--release -p carrier -p jedi -p dumpy -p turtl_core" test
      - run: make SODIUM_STATIC=static release
      - save_cache:
          key: core-build-v3-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/
            - target/

      - run: mkdir -p ../workspace
      - run: cp target/release/libturtl_core.so ../workspace
      - run: cp config.yaml ../workspace
      - persist_to_workspace:
          root: /tmp/turtl/
          paths:
            - workspace

  test:
    <<: *defaults

    docker:
      - image: circleci/node:4.8.3
      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER=turtl
          - POSTGRES_DB=turtl

    steps:
      - attach_workspace:
          at: /tmp/turtl

      - checkout

      - run: mkdir -p target/release/
      - run: cp ../workspace/libturtl_core.so target/release/
      - run: cp ../workspace/config.yaml .

      # set up/run server
      - run: git clone https://github.com/turtl/server ../server
      - run: cp ../server/config/config.yaml.ci ../server/config/config.yaml
      - restore_cache:
          key: server-npm-v1-{{ checksum "../server/package.json" }}
          key: server-npm-v1-
      - run: cd ../server && npm install
      - save_cache:
          key: server-npm-v1-{{ checksum "../server/package.json" }}
          paths:
            - ../server/node_modules
      - run: mkdir -p ../server/plugins
      - run: mkdir -p ../server/public/uploads
      - run: sleep 5
      - run: node ../server/tools/create-db-schema.js
      - run: node ../server/tools/populate-test-data.js
      - run:
          command: node ../server/server.js
          background: true

      # install rust
      - run: gpg --import build-tools/rust.gpg.pub
      - run: wget https://static.rust-lang.org/rustup.sh -O /tmp/rustup.sh && chmod 0750 /tmp/rustup.sh
      - run: sudo /tmp/rustup.sh --revision=1.24.1

      - run: |
          cd integration-tests
          mkdir -p /tmp/turtl/integration
          make \
            RUST_BACKTRACE=1 \
            TURTL_LOGLEVEL=info \
            TURTL_CONFIG_FILE=../config.yaml \
            LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:../target/release" \
            test

      - run: cp config.yaml.default ../workspace/config.yaml
      - run: cp clippo/parsers.yaml ../workspace/
      - persist_to_workspace:
          root: /tmp/turtl/
          paths:
            - workspace

  deploy:
    <<: *defaults

    docker:
      - image: circleci/node:4.8.3

    steps:
      - attach_workspace:
          at: /tmp/turtl
      - run: echo "ALL DONE LOL"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v[0-9]/

