[package]
name = "migrate"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[lib]
name = "migrate"
crate-type = ["rlib"]
doctest = false				# these annoy me

[dependencies]
config = { path = "../config" }
fern = "0.3.5"
gcrypt = "0.3.0"
hyper = "0.9.18"
jedi = { path = "../jedi" }
lazy_static = "0.2.1"
log = "0.3.6"
quick-error = "1.1.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

