[package]
name = "scraper"
version = "0.4.0"

description = "HTML parsing and querying with CSS selectors"
keywords = ["html", "css", "selector", "scraping"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

documentation = "https://cmcenroe.me/scraper/scraper"
repository = "https://github.com/programble/scraper"
readme="README.md"

[dependencies]
cssparser = "0.5.0"
ego-tree = "0.1.0"
html5ever = "0.5.0"
selectors = "0.5.0"
string_cache = "0.2.5"
tendril = "0.2.1"
