[package]
name = "sock"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
cwrap = { path = "../cwrap" }
log = "0.4.1"

[dependencies.websocket]
version = "0.20.2"
default-features = false
features = ["sync"]

